import pickle
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.remote.webelement import WebElement
from copy import deepcopy

def arrangeData():
    books: str
    try:
        with open("BooksData/RawData.pkl", "rb") as file:
            books = pickle.load(file)
    except:
        books = """Var mısın? / Doğan Cüceloğlu( Kronik Kitap 2021 )
        Hunlar Hakanı Attila / Nic Fields( Kronik Kitap 2021 )
        Haçlı Devletleri Tarihi / Malcolm Barber( Kronik Kitap 2021 )
        Tabgaçlar / Tuğba Gökçe Balcı( Kronik Kitap 2021 )
        Pompeius / Nic Fields( Kronik Kitap 2021 )
        Habsburglar / Martyn Rady( Kronik Kitap 2021 )
        Stalin'in Savaşı / Sean Mcmeekin( Kronik Kitap 2021 )
        Evimiz Yanıyor / Greta Thunberg( Kronik Kitap 2021 )
        Napoleon Bonaparte / Gregory Fremont-Barnes( Kronik Kitap 2021 )
        Dante / Alessandro Barbero( Kronik Kitap 2021 )
        Yeniçeri / Yaşar Metin Aksoy( Kronik Kitap 2021 )
        Hannibal / Nic Fields( Kronik Kitap 2021 )
        Sultan II. Murad / M. Tayyib Gökbilgin( Kronik Kitap 2021 )
        Eski Çağın Büyük Komutanları / Andrew Roberts( Kronik Kitap 2021 )
        Osmanlı'da İktisadî Hayat ve Vakıflar / Kerim İlker Bulunur-Ömer Faruk Can( Kronik Kitap 2021 )
        İşi Ustasından Öğrenin / Frank Arnold( Kronik Kitap 2021 )
        Samuraylar / Stephen Turnbull( Kronik Kitap 2021 )
        Çağrı Bey / Cihan Piyadeoğlu( Kronik Kitap 2021 )
        Selâhaddîn Eyyûbî / David Nicolle( Kronik Kitap 2021 )
        Fâtimî İmparatorluğu / Michael Brett( Kronik Kitap 2021 )
        Binu ve Büyük Sur / Su Tong( Alfa Yayınları 2021 )
        Teknoloji Nasıl Çalışır? / Kolektif( Alfa Yayınları 2021 )
        Bilimin Sihirbazları / Marcus Chown( Alfa Yayınları 2021 )
        Reformasyon Dünyası / Andrew Pettegree( Alfa Yayınları 2021 )
        Sanat Tarihinin Elli Temel Metni / Diana Newall, Grant Pooke( Ayrıntı Yayınları 2021 )
        Kayıp Hafızanın İzinde / Pınar Yıldız( Metis Yayınları 2021 )
        Bir Ağacın Altında / Selçuk Demirel( Yapı Kredi Yayınları 2021 )
        Çocuk Düşmanlığı: Çocuklara Karşı Önyargıyla Yüzleşme / Elisabeth Young-Bruehl( İletişim Yayınları 2021 )
        Avrupa'nın Entelektüel Tarihi: 19. ve 20. Yüzyıl / François Chaubet( İletişim Yayınları 2021 )
        Komplo Teorilerinin Psikolojisi / Jan-Willem van Prooijen( Nobel Yaşam Yayınları 2021 )
        Hatıraların Evi / Kemal Sayar( Kapı Yayınları 2022 )
        Başı Sınuklar İçin Kılavuz / Kemal Sayar( Kapı Yayınları 2021 )
        Einstein Ansiklopedisi / Alice Calaprice, Daniel Kennefick, Robert Schulmann ( Alfa Yayınları 2022 )
        İlkel Sanat / Franz Boas( Ayrıntı Yayınları 2021 )
        Beton Çocuklar / Amyra Léon( Kolektif Kitap 2021 )
        Sayılar ve Türümüze Katkıları / Caleb Everett( Kolektif Kitap 2021 )
        Sessiz Güç / Susan Cain( Pegasus Yayınları 2021 )
        Almanca Seyahatnamelerde Osmanlı Şehirleri (1850-1912) / Aysel Kaya( İletişim Yayınları 2021 )
        Sokağın Sesleri: Osmanlı'dan Günümüze Sokak Müziği / Sedat Anar( İletişim Yayınları 2021 )
        Kültürlerarası İletişim: Kullanım Kılavuzu / Michel Bourse, Halime Yücel( İletişim Yayınları 2021 )
        Gerçekçiliğe Yeni Bir Çağrı: Salgın Günlerinde Felsefe / Kolektif( Nobel Yayınları 2021 )
        Tarihin Doğal Deneyleri / Jared Diamond-James A. Robinson( Pegasus Yayınları 2021 )
        Tüm Soruların Anası / Rebecca Solnit( Siren Yayınları 2022 )
        Kendin Olma Hakkı / Terri Cole( Okuyan Us Yayınları 2022 )
        Kimse Normal Değil / Roy Richard Grinker( Okuyan Us Yayınları 2022 )
        Afrika Devrimine Doğru / Frantz Fanon( Sel Yayıncılık 2022 )
        Bir Üretim Mekânı Olarak: Beyoğlu Düşerse / Burcu Pelvanoğlu( Sel Yayıncılık 2022 )
        Uykuya Övgü: Uykusu Kaçanlar İçin Kullanım Kılavuzu / Dalibor Frioux( Sel Yayıncılık 2022 )
        Tarih Ne İşe Yarar? / Ahmet Şimşek( Kapı Yayınları 2022 )
        Bitki Ulusu / Stefano Mancuso( Alfa Yayınları 2022 )
        Evrimin Kısa Tarihi / Tamer Kaya( Alfa Yayınları 2022 )
        Bilimin Yedi Dayanağı / John Gribbin( Alfa Yayınları 2022 )
        Altı Olasılıksız Şey / John Gribbin( Alfa Yayınları 2022 )
        İnsanın İnanılmaz Yolculuğu / Alice Roberts( Alfa Yayınları 2022 )
        Türlerin Yeni Kökeni / Torill Kornfeldt( Alfa Yayınları 2022 )
        Ortadoğu'da Sosyal Adalet ve Siyasal İktidarın Tarihi / Linda T. Darling( Alfa Yayınları 2022 )
        Varoluşun Halleri / Kaan H. Ökten( Alfa Yayınları 2022 )
        Para ve Akdeniz Uygarlığı / Carlo M. Cipolla( Alfa Yayınları 2022 )
        Ekoloji Kitabı / Kolektif( Alfa Yayınları 2021 )
        Alfred Hitchcock / Peter Ackroyd( Alfa Yayınları 2021 )
        Çağdaş Sanat: Bir Tarihçe / Julian Stallabrass( İletişim Yayınları 2021 )
        Troya Savaşı / Barry Strauss( Kronik Kitap 2021 )
        Manşetlerden Gaipliğe: Bay-Bayan Kenan Çinili’nin Evrak-ı Metrukesi / Serdar Soydan( Sel Yayıncılık 2021 )
        Bizim Filmlerimiz Onların Filmleri / Satyajit Ray( Vakıfbank Kültür Yayınları 2022 )
        Adaletsizliğin Veçheleri / Judith N. Shklar( Vakıfbank Kültür Yayınları 2022 )
        Çok Hisseden Çocuk / Lorenz Wagner( Timaş Yayınları 2022 )
        Kendini Bilmek / Stephen M. Fleming( Timaş Yayınları 2022 )
        Dijital Beden Dili / Erica Dwahan( Timaş Yayınları 2022 )
        İncelikler Tarihi Gülten Akın Şiiri / Asuman Susam, Duygu Kankaytsın, haz.( Yapı Kredi Yayınları 2022 )
        Büyütücü Mercek – Proust Üstüne Yeni Yazılar / Mehmet Rifat( Yapı Kredi Yayınları 2022 )
        Gelecekten Gelen Şiir / Srécko Horvat( Kolektif Kitap 2021 )
        Novasen: Yaklaşan Hiperzekâ Çağı / James Lovelock( Kolektif Kitap 2021 )
        Mimesis İfade ve Gösterge / Servet Gündoğdu( Hece Yayınları 2021 )
        Meraklısına Drama Atölyeleri / Kolektif( Altın Kitaplar 2021 )
        Antik Roma / Umberto Eco( Alfa Yayınları 2021 )
        Hayatta Kalma Sanatçıları: 20. Yüzyıldan 99 Edebî Vinyet / Hans Magnus Enzensberger( İletişim Yayınları 2021 )
        Veganizm / Valéry Giroux, Renan Larue( İletişim Yayınları 2021 )
        İnsan-Hayvan ve Ötesi / Kiraz Özdoğan ( Kolektif Kitap 2021 )
        Melankoli / Serol Teber( Okuyan Us Yayınları 2022 )
        Dijital Yorgunluk / Kemal Sayar, Berna Yalaz( Kapı Yayınları 2022 )
        Kafkas Halk Destanları / Anonim( Vakıfbank Kültür Yayınları 2022 )
        Berlin'in İlk Günleri / Ulrich Gutmair( Kolektif Kitap 2022 )
        Sapiens: Grafik Tarih 2 / Yuval Noah Harari( Kolektif Kitap 2022 )
        Hayvanlar Nasıl Düşünür, İnsan Ne Görür? / Loic Bollache( Timaş Yayınları 2022 )
        Büyük Kaos: İklim Değişikliği ve Hiç Düşünülmeyenler / Amita Ghosh( Timaş Yayınları 2022 )
        Yalnızlık ve Aidiyet / Oğuz Tan( Timaş Yayınları 2022 )
        Kadîm ile Cedîd Arasında – III. Selim Döneminde Bir Mevlevi Şeyhi: Abdülbâki Nâsır Dede’nin Musıki Yazmaları / Cem Behar( Yapı Kredi Yayınları 2022 )
        Birdenbire İstanbul / Selçuk Demirel( Yapı Kredi Yayınları 2022 )
        İlk Modern Osmanlı – Ahmed Vâsıf’ın Fikri Gelişimi / Ethan L. Menchinger( Yapı Kredi Yayınları 2022 )
        Araplar – Kavimler, Kabileler ve Devletlerin Üç Bin Yıllık Tarihi / Tim Mackintosh Smith( Yapı Kredi Yayınları 2022 )
        Kadınca Bilmeyişlerin Sonu: 1960-1980 Döneminde Feminist Edebiyat / Duygu Çayırcıoğlu( İletişim Yayınları 2022 )
        Brütalizm / Achille Mbembe( İletişim Yayınları 2022 )
        Hegel ve Modern Toplum / Charles Taylor( Kolektif Kitap 2021 )
        Sessiz / Susan Cain( Pegasus Yayınları 2021 )
        İnsanda ve Hayvanlarda Duyguların İfade Edilmesi / Charles Darwin( Alfa Yayınları 2021 )
        Zihnin Arkeolojisi / Jaak Panksepp, Lucy Biven( Alfa Yayınları 2021 )
        Türk Mimarisinin Kısa Tarihi / Yaşar Çoruhlu( Alfa Yayınları 2021 )
        Esperanto ve Çokdilli Bir Gelecek / Umberto Eco( Alfa Yayınları 2021 )
        Bizans'ın Sonu / Jonathan Harris( Alfa Yayınları 2021 )
        Popüler Sinema’nın Mitolojisi 2 / Veysel Atayman, Tuncer Çetinkaya( Ayrıntı Yayınları 2021 )
        Sanayi, Sanayileşme ve Teknoloji / İşaya Üşür( Dost Kitabevi 2021 )
        Yolumuzu Değiştirelim-Koronavirüsün Öğrettikleri / Edgar Morin( Türkiye İş Bankası Kültür Yayınları 2021 )
        Sonsuz Uzayın Hâkimi / Raymond Tallis( Türkiye İş Bankası Kültür Yayınları 2021 )
        Çeviriyi Düşünmek / Mehmet Rifat( Sel Yayıncılık 2021 )
        Güzel Yaşam Kılavuzu-Antik Stoacı Sevinç Sanatı / William B. Irvine( Türkiye İş Bankası Kültür Yayınları 2022 )
        Modern Dünyanın Krizi / René Guénon( Kapı Yayınları 2022 )
        Alman Düşüncesinde Sanat ve Aşkınlık / Ömer B. Albayrak( Alfa Yayınları 2022 )
        Tesadüfün Böylesi / Brian King, Martin Plimmer( Alfa Yayınları 2022 )
        Yeni Düzende Girişimcilik / Berke Sarpaş( Alfa Yayınları 2022 )
        Romalıların Kısa Tarihi / Kolektif( Alfa Yayınları 2022 )
        Çağımız ve Thomas Hobbes / M. Ertan Kardeş( Vakıfbank Kültür Yayınları 2022 )
        Vahşiler ve Duygusallar / Javier Marías( Yapı Kredi Yayınları 2022 )
        Sanat ve Ekoloji: Sanat/Yaşam/Üretim / Eda Sezgin, der.( İletişim Yayınları 2022 )
        İyi Hisset, İyi Yaşa / Vex King( Pegasus Yayınları 2021 )
        Dante-Seküler Dünyanın Şairi / Erich Auerbach( Alfa Yayınları 2021 )
        Başlangıçta Hidrojen Vardı / Hoimar von Ditfurth( Alfa Yayınları 2021 )
        E. T. A. Hoffmann / Rüdiger Safranski( Alfa Yayınları 2021 )
        Profesör Stewart'ın İnanılmaz Sayıları / Ian Stewart( Alfa Yayınları 2021 )
        Parlak Yıldızlardık O Zaman: Kültür Çalışmaları - Meral Özbek'e Armağan / Tülin Ural, Bahadır Vural( İletişim Yayınları 2021 )
        Haneden Ev Haline: “Türk Evi"nde Mimari, Düzenleme, Pratik / Seyhan Kurt( İletişim Yayınları 2021 )
        İnsan Türleriyle Yakın Temas / Sang-Hee Lee, Shin-Young Yoon( Metis Yayınları 2021 )
        Yatak Odasındaki Kalabalık / Yeliz Turan Yunusoğlu( Metis Yayınları 2021 )
        İnsan Denen Hayvan / Barbara Natterson-Horowitz, Kathryn Bowers( Metis Yayınları 2021 )
        Emek, Beden, Aile: Türkiye’de Kadınlık Halleri / Taylan Acar, Şemsa Özar( Metis Yayınları 2021 )
        Balıkların Bildikleri / Jonathan Balcombe( Metis Yayınları 2021 )
        Umut Günlükleri: Filistin’de Yaşam ve Ölüm / Ben Ehrenreich( Epsilon Yayınevi 2021 )
        Uygarlığın Ayak İzleri: Batı Resminde Aşk ve Bazı Küçük Felaketler / Celil Sadık( Epsilon Yayınevi 2021 )
        Evrensel İstisna: Radikal Siyaset Okumaları / Slavoj Zizek( MonoKL Yayınları 2021 )
        Marx Okumak / Slavoj Žižek - Frank Ruda - Agon Hamza( Kolektif Kitap 2021 )
        Sufi Sinema / Yunus Özmodanlı( Hece Yayınları 2021 )
        Zaman İçinde Mekân / Bilal Can( Hece Yayınları 2021 )
        Bitkisel Hafıza ve Bibliyofili Üzerine / Umberto Eco( Alfa Yayınları 2021 )
        Hayatın İlk Üç Yılı / Bahar Eriş( Alfa Yayınları 2021 )
        Lucifer'in Mirası / Frank Close( Alfa Yayınları 2021 )
        İstanbul Açık Şehir: Kentsel Modernitenin Endişelerini Sergilemek / İpek Türeli( Metis Yayınları 2021 )
        Coğrafi Bir Mesele Olarak Mimarlık / Nevzat Sayın( Yapı Kredi Yayınları 2021 )
        Yıldız Hikâyeleri – Dünya Kültürlerinde Takımyıldızlar / Erdem Gökyaran( Yapı Kredi Yayınları 2021 )
        Yemeğin Psikopolitikası: Neoliberal Çağda Yemek Ritüelleri / Mihalis Mentinis( Ayrıntı Yayınları 2021 )
        Şüphenin Tarihi – Felsefeye Giriş / Sadık Usta( Epsilon Yayınevi 2021 )
        Plastik Kriziyle Mücadele Etmek / Hannah Testa( Kolektif Kitap 2021 )
        Sessizliğin Tarihi / Alain Corbin( Kolektif Kitap 2021 )
        Nasıl Hata Yapmazsınız / Jordan Ellenberg( Pegasus Yayınları 2021 )
        Pandemi / Michael Greger( Altın Kitaplar 2021 )
        İbni Haldun / Robert Irwin( Alfa Yayınları 2021 )
        Otur Kızım-Kadın Düşmanlığının Mantığı / Kate Manne( Alfa Yayınları 2021 )
        Türk Sosyolojisinin Kısa Tarihi / Yücel Bulut( Alfa Yayınları 2021 )
        Açıklığa Doğru / Asuman Susam( Everest Yayınları 2021 )
        Tırışkadan İşler / David Graeber( Everest Yayınları 2021 )
        Delişmenlik Çağı: Ergenlikten Erişkinliğe İnsanların ve Diğer Hayvanların Destansı Yolculuğu / Barbara Natterson-Horowitz, Kathryn Bowers( Metis Yayınları 2021 )
        Gecikmeye Övgü – Zaman Nereye Gitti? / Hélène L’Heuillet( Yapı Kredi Yayınları 2021 )
        Dünya Tarihi ve Siyaset / Huricihan İslamoğlu( İletişim Yayınları 2021 )
        Mutfakta Bir Dilim Farkındalık / Isabelle Filliozat( Pegasus Yayınları 2021 )
        Yıldızların Çocukları: Evrenin ve İnsanlığın Kökenine Harika Bir Yolculuk / María Teresa Ruíz( Babil Kitap 2021 )
        Riske Övgü / Anne Dufourmantelle ( Kolektif Kitap 2021 )
        Mahalle Odaklı Katılım 5.0 / Kolektif( Kolektif Kitap 2022 )
        Hayata Nereden Bakmalıyız?: Yeni Bir Dünya İçin On Eski Fikir / Svend Brinkmann( İletişim Yayınları 2022 )
        Dijital Oyunlarda Empatik İletişim / Aslı İgit( Nobel Akademik Yayıncılık 2022 )
        August Hermann Francke / Tibet Kültürü( Maya Kitap 2022 )
        George Tradescant Lay / Çin Kültürü( Maya Kitap 2022 )
        Daniel Garrison Brinton / Kızılderili Mitolojisi ( Maya Kitap 2022 )
        Ücret Patriyarkası / Silvia Federici( Sel Yayıncılık 2022 )
        Biyoloji Kitabı / Kolektif( Alfa Yayınları 2023 )
        Dünya Bitkileri / Stefano Mancuso( Alfa Yayınları 2022 )
        Kahramanlar / Stephen Fry( Alfa Yayınları 2022 )
        Evrenin Kodunu Kırmak / John W. Moffat( Alfa Yayınları 2022 )
        Düzenin Kökenleri / Stuart A. Kauffman( Alfa Yayınları 2022 )
        Kayıp Destan’ın İzinde – Nâzım Hikmet, İdeoloji ve Yeniden Yazmak / Erkan Irmak( Yapı Kredi Yayınları 2022 )
        Şiir Neden Önemlidir? / Jay Parini( Yapı Kredi Yayınları 2022 )
        Cumhuriyet ve Hissiyat Falih Rıfkı Atay'da Modernlik, Ulus ve Duygular / Hikmet Çağrı Yardımcı( İletişim Yayınları 2022 )
        Gladyatörler / Arthur Koestler( İletişim Yayınları 2022 )
        Eşyaların Patriyarkası: Dünya Kadınlara Neden Uymaz? / Rebekka Endler( İletişim Yayınları 2022 )
        Osmanlılar Dönemi’nde Teknoloji / Remzi Demir, Melek Dosay Gökdoğan( Noel Akademik Yayıncılık 2023 )
        Yüzeysel - Toplumsal Tipikler / Haydar Ergülen( Karakarga Yayınları 2022 )
        Kötülüğün Öğretmeni: Machiavelli Üzerine Düşünceler / Leo Strauss ( Babil Kitap 2023 )
        Pastayı Büyüt / Alex Edmans( Doğan Kitap 2023 )
        Evcilleştirme / Alice Roberts( Epsilon Yayınevi 2022 )
        İstanbul Seyahatnamesi: 19. Yüzyılda Rus Seyyahlarla Osmanlı Topraklarına Yolculuk / Kolektif( Kronik Kitap 2022 )
        Antik Çin ve Düşmanları / Nicola Di Cosmo( Kronik Kitap 2022 )
        Neden Tüketiyoruz / Cenk Koçaş( Doğan Kitap 2023 )
        Claude Monet: Sanatçının Gördükleri / Amy Guglielmo( Everest Yayınları 2023 )
        Joshua Sperling / John Berger: Zamanımızın Bir Yazarı ( Everest Yayınları 2022 )
        İnsan Yıkıcılığı / Anthony Storr( Alfa Yayınları 2022 )
        Nova Roma’da Gece Güneşi / Lâle Müldür( Yapı Kredi Yayınları 2023 )
        Moğolların Kısa Tarihi / George Lane( İletişim Yayınları 2022 )
        Ortak Gelecek: Sürdürülebilir Bir Dünya İçin Parlak Fikirler, Büyük Etkiler / Ilgaz Gürsoy ( Pegasus Yayınları 2022 )
        Toplumsal Cinsiyet Eşitsizliğinin Farklı Yüzleri - Psikolojik Yaklaşımlar / Kolektif ( Noel Akademik Yayıncılık 2022 )
        Çağdaş Türk Romanında Teknolojik Gerçeklik / Koray Üstün ( Noel Akademik Yayıncılık 2022 )
        Kaygan Uzamda Hareketler: Deleuze ve Guattari Üzerine Çalışmalar / Süreyya Su( Noel Akademik Yayıncılık 2022 )
        Hakikat Krizinde Entelektüel ve Öteki: Vives-Goethe / Jose Ortega Y Gasset ( Babil Kitap 2023 )
        Gökbilimsel / Tim James( Timaş Yayınları 2022 )
        Rusya Seyahatnamesi / Abdulahad Bahadır Han( Kronik Kitap 2023 )
        Aztekler / Camilla Townsend( Kronik Kitap 2023 )
        Dünyayı Değiştiren Kararlar / Ian Kershaw( Kronik Kitap 2022 )
        Türkiye'de Sinemanın Tarihi / Savaş Arslan( Kronik Kitap 2022 )
        Kara Ölüm : Ortaçağ Dünyasını Yok Olmanın Eşiğine Getiren Veba / Tolgahan Karaimamoğlu( Kronik Kitap 2022 )
        Burada Manzara Harika / Neşe Cehiz( İletişim Yayınları 2022 )
        Dâhilerin Gizli Alışkanlıkları / Craig Wright( Kronik Kitap 2022 )
        Güney Afrika'da Osmanlı İzleri / Halim Gençoğlu( Kronik Kitap 2022 )
        Germania - Britannia: Hatipler Üzerine Diyaloglar / Cornelius Tacitus( Kronik Kitap 2022 )
        Eski Türklerde Gündelik Hayat / Erhan Aydın( Kronik Kitap 2022 )
        Gezegenimizden Bir Yaşam - Tanıklık Ettiklerim ve Geleceğe Dair Bir Vizyon / David Attenborough( Kronik Kitap 2022 )
        Doğanın Dönüşü-2 / John Bellamy Foster( Kalkedon Yayınları 2022 )
        William Tyler Olcott / Güneş Mitleri( Maya Kitap 2022 )
        Grimmlerin Mirası / Jack Zipes( Alfa Yayınları 2023 )
        Etimoloji Işığında Kelimelerin Dünyasında Gezintiler / Bülent Aksoy( İletişim Yayınları 2022 )
        Hafif Kahramanlar / Aksu Bora, Emel Uzun, der.( İletişim Yayınları 2023 )
        Gözünüzü Ay’a Dikin: İnsanoğlunun Ay’a Çıkmasını Sağlayan 8 Başarı İlkesi / Richard Wiseman ( Pegasus Yayınları 2023 )
        Metaverse: Geleceğin Dünyalarını İnşa Edecek Teknolojiler, Fırsatlar ve Tehditler / Kolektif ( Noel Akademik Yayıncılık 2022 )
        Yaşlılık Psikolojisini Anlamak / Kolektif( Noel Akademik Yayıncılık 2022 )
        Roland Barthes / Tiphaine Samoyault( Everest Yayınları 2022 )
        Benim Hayatım Hep Böyle mi Geçecek? / İbrahim Bilgen( Epsilon Yayınevi 2023 )
        Tablodaki Kadın: Sanat Tarihinin Kitap Tutkunu Kadınları / Asuman Kafaoğlu-Büke( Epsilon Yayınevi 2022 )
        Zihnin Mekanizması / Edward De Bono( Epsilon Yayınevi 2022 )
        Tarihteki Garip Vakalar / Max Kemmerich( Timaş Yayınları 2023 )
        Bizans Tarihi: Agathias Kroniği 552-559 / Myrinalı Agathias( Timaş Yayınları 2023 )
        Akrep ve Yelkovanın İzinde / David Rooney( Timaş Yayınları 2022 )
        Osmanlı Hava Gücü / Erich Serno( Kronik Kitap 2022 )
        Öngörülemeyen Bir Dünyada Yaşamak / Frederic Lenoir( Türkiye İş Bankası Kültür Yayınları 2023 )
        Bir Sanat Olarak Ebeveyn Baskısı / Chris Thurber( Okuyan Us Yayınları 2023 )
        Çünkü O Daha Çocuk / Senem Han Uysal( Doğan Kitap 2023 )
        O An / Barış Muslu( Doğan Kitap 2023 )
        Doğaya Açılan Pencere: İzlenimci Ressamların Peşinde / Nedim Gürsel( Doğan Kitap 2023 )
        Yapay Zekâ ve Kapitalizmin Geleceği: İnsandışı Bir Güç / Nick Dyer-Witheford, Atle Mikkola Kjøsen, James Steinhoff( İletişim Yayınları 2022 )
        Dostluk Felsefesi / Kenan Göçer( Pan Yayıncılık 2022 )
        Öz Terapi / Binnur Yeşilyaprak( Nobel Kültür 2022 )
        Doğu’ya Yolculuk: 15. Yüzyılda Kıpçak Bozkırı, İran ve Doğu Anadolu’ya Seyahat / Giosafat Barbaro ( Kronik Kitap 2022 )
        Sürgün / Turan Akıncı( Remzi Kitabevi 2022 )
        Masaharu Anesaki / Japon Kültürü( Maya Kitap 2022 )
        Daniel G. Brinton / Kahramanlık Mitleri( Maya Kitap 2022 )
        İnsan Ada Değildir / Nuccio Ordine( Alfa Yayınları 2023 )
        İktidar Tohumları: Osmanlı Çevre Tarihi Üzerine İncelemeler / Onur İnal, Yavuz Köse, der.( İletişim Yayınları 2022 )
        Mekanda Yitmek Dilde Barınmak: Mültecilik ve Çocuk Edebiyatı / Ferhat Çiftçi ( Noel Akademik Yayıncılık 2023 )
        O Sırada: Üçüncü Kitap: Sonsuza Kadar Pazar Sabahı ve Diğer Yazılar / Erman Çağlar( Karakarga Yayınları 2022 )
        Rothschild Hanedanı / Niall Ferguson( Kronik Kitap 2023 )
        Van'ın Yitik Dünyası / Osep Tokat( İnkılâp Kitabevi 2023 )
        Sultanın Saatçisi Meyer Saatlerinin Asırlık Öyküsü / Serkan Yazıcı( Kronik Kitap 2023 )
        Moğol Savaş Sanatı / Timothy May( Kronik Kitap 2023 )
        Sanat Tarihi: Büyülü Tuvaller Sihirli Keskiler / Stepanka Sekaninova( Kronik Kitap 2023 )
        Uzayda / Gezegenimizden Uzaya Yolculuk Eden İlk İnsanın Çarpıcı Hikâyesi / Stephen Walker( Kronik Kitap 2023 )
        Büyük Strateji  / John Lewis Gaddis( Epsilon Yayınevi 2023 )
        Felsefenin Kraliçeleri Felsefe Tarihinde Kadın Filozoflar Nerede? / Lisa Whiting, Rebecca Buxton( Epsilon Yayınevi 2023 )
        Dört Bin Hafta: Ölümlüler İçin Zaman Yönetimi / Oliver Burkeman( Epsilon Yayınevi 2023 )
        Talihe Zar Atmak: Tanzimat'tan Erken Cumhuriyet'e Kumar / Ahmet Yeşilyurt( İletişim Yayınları 2022 )
        Eşitsizlikler Kitabı: 2000'ler Türkiyesi'nde Gelir, Tüketim ve Değişim / Oğuz Işık( İletişim Yayınları 2022 )
        Karanlık Zamanlarda İnsanlar / Hannah Arendt( İletişim Yayınları 2022 )
        Nihilizm / Nolen Gertz( Pan Yayıncılık 2022 )
        Yaratıcı Düşüncenin Gelişimi / Faruk Malhan( Nobel Kültür 2022 )
        Winifred Stephens / Budizm Efsaneleri ( Maya Kitap 2022 )
        Lafcadio Hearn / Japonya'nın Hayaletleri( Maya Kitap 2022 )
        William D. Westervelt / Hawaii Mitleri( Maya Kitap 2022 )
        Troya-En Büyük Hikâyemiz / Stephen Fry( Alfa Yayınları 2023 )
        İnovasyonun Kısa Tarihi / Matt Ridley( Alfa Yayınları 2022 )
        Durdurulamayan İnsanlık / Yuval Noah Harari( Kolektif Kitap 2022 )
        Gertrude Stein / Philippe Blanchon( Yapı Kredi Yayınları 2022 )
        Kadın Çalışmaları: Temeller / Bonnie G. Smith( İletişim Yayınları 2022 )
        Lavinia / Haluk Oral( Everest Yayınları 2023 )
        Bilimin Bilinmeyen Tarihi / Burak Saytekin( Epsilon Yayınevi 2022 )
        Zabel Yaseyan Yaşamı ve Eserleri / Sosi Antikacıoğlu( İnkılâp Kitabevi 2022 )
        Fotoğrafların Anlattığı-Aile Belleğini Yeniden Okumak / Christine Ulivicci( Türkiye İş Bankası Kültür Yayınları 2023 )
        Şaşmaz Bilimcinin El Kitabı / R. Philip Bouchard( Okuyan Us Yayınları 2023 )
        Bernard Montgomery / Osprey: Büyük Komutanlar / Tim Moreman( Kronik Kitap 2023 )
        Kısa Japonya Tarihi / Jonathan Clements( Kronik Kitap 2023 )
        "Fesi Düşürmeden": Pakrat Estukyan Anlatısı / Elif Atalay( İletişim Yayınları 2022 )
        Sen Benim Kim Olduğumu Biliyor musun?: Kibrin Tarihi / Ari Turunen( İletişim Yayınları 2022 )
        İnsan Birikimdir-Bir Genel Yayın Yönetmeninin Gözünden Yazma ve Okuma Deneyimi / Ertürk Akşun( Karakarga Yayınları 2022 )
        An / Deniz Altınay ( Nobel Akademik Yayıncılık 2022 )
        Başkasının Zararına Sevinme - Schadenfreude / Seda Erzi( Nobel Akademik Yayıncılık 2022 )
        Antik Yunan’da Felsefe, Bilim ve Sanat / Suat Soner Erenözlü( Nobel Akademik Yayıncılık 2022 )
        Uzay Yolculuğu - İnsanlığın Evreni Keşfinin Kısa Tarihi / Paul Parsons( Kronik Kitap 2022 )
        Nüzhet / Arın Dilligil Bayraktaroğlu( Remzi Kitabevi 2022 )
        Maud İsabel Ebbutt / Britanya Kahramanları ( Maya Kitap 2022 )
        Hisseden Beyin / Mark Solms( Okuyan Us Yayınları 2022 )
        Hareketliliğin Doğası / Kolektif( Alfa Yayınları 2023 )
        Osmanlı‘dan Erken Cumhuriyet‘e Hayvan Katliamları ve Himaye Kediler, Köpekler, Kargalar / Ömer Obuz( İletişim Yayınları 2022 )
        Çin Mucizesinin Sonu mu?: Uyuyan Aslan, Kâğıttan Kaplan / Cevdet Kadri Kırımlı( İletişim Yayınları 2023 )
        Weimar Kültürü / Peter Gay( İletişim Yayınları 2023 )
        Mekanda Yitmek Dilde Barınmak: Mültecilik ve Çocuk Edebiyatı / Ferhat Çiftçi ( Noel Akademik Yayıncılık 2023 )
        Kendimle Karşılaşmalar / Arzu Erkan( Karakarga Yayınları 2022 )
        Vicdan Bir Kara Kutudur - Robert Oppenheimer / Mesud Topal( Karakarga Yayınları 2022 )
        Edebiyatla Felsefe Arasında / Hilmi Yavuz( Everest Yayınları 2022 )
        Rodos Kuşatması / Mehmet Yaşar Ertaş( Timaş Yayınları 2022 )
        Roma İmparatorları 3: Valerianus'tan Carinus'a / Historia Augusta( Kronik Kitap 2022 )
        İnsanlığın Serüveni: Zenginliğin ve Eşitsizliğin Tarihi / Oded Galor( Kronik Kitap 2022 )
        Orta Çağ Avrupası / Özlem Genç( Kronik Kitap 2022 )
        Göçmen Figürü / Thomas Nail( İletişim Yayınları 2022 )
        Yunan Mitolojisi / Burcu Camcı ve Leonidas Galariotis( Karakarga Yayınları 2022 )
        Moda ve Ekonomi / Zeynep Ökten( Nobel Akademik Yayıncılık 2022 )
        Dünyanın En Mutlu Adamı: Bir Auschwitz Mahkûmunun Umut Veren Yaşam Öyküsü / Eddie Jaku ( Kronik Kitap 2022 )
        Engizisyon Kıskacında Katharlar / Göksel Sarı( Kalkedon Yayınları 2021 )
        Kafka Sinemaya Gidiyor / Hanns Zischler( Everest Yayınları 2022 )
        Yüzmek, Yaşamak ve Olma Arzusu / Nihan Kaya( Eksik Parça Yayınları 2022 )
        Dünya- Antropolojik Bir İnceleme / Pina Cabral( Kapı Yayınları 2022 )
        Hoşgörüsüzlüğe Hayır / Kolektif( Alfa Yayınları 2022 )
        Çalışma / James Suzman( Kolektif Kitap 2022 )
        Başkaldıran Yalnız Adam Albert Camus ve Çağdaşları / Mehmet Rifat( Yapı Kredi Yayınları 2023 )
        Burada Manzara Harika / Neşe Cehiz( İletişim Yayınları 2022 )
        Küçük Yuvarlak Taşlar / Melisa Kesmez( İletişim Yayınları 2022 )
        İklim Değişikliği Bağlamında Küresel ve Yerel Yansımalar / Kolektif ( Noel Akademik Yayıncılık 2022 )
        Kitap, Hitap, Hakikat / Adonis( Everest Yayınları 2022 )
        Yazarın Yol Haritası / Kolektif( Timaş Yayınları 2023 )
        Demir Çağı'ndan Kartaca Savaşlarına Roma'nın Yükselişi / Katharyn Lomas( Kronik Kitap 2022 )
        Yüz Yıl Savaşları: Avrupa'yı Şekillendiren İngiliz-Fransız Mücadelesi / Michael Prestwich( Kronik Kitap 2022 )
        Göçün Tarihi / Michael H. Fisher( İnkılâp Kitabevi 2022 )
        Az Su İsteyen Bahçeler / Gülnar Onay( İnkılâp Kitabevi 2022 )
        Aslında Öyle Değil / Aylin Algun( İnkılâp Kitabevi 2022 )
        Bariatrik Manifesto / Ahmet Türkçapar, Berk Özler( İnkılâp Kitabevi 2022 )
        Şehirlerin Tarihi / Andrew Lees( İnkılâp Kitabevi 2022 )
        Erteleme-Nedenleri ve Çözümleri / Nihan Kaya( Eksik Parça Yayınları 2023 )
        Görsel Metodoloji / Gillian Rose( İnkılap Kitabevi 2023 )"""
        books = books.replace("â","a").replace("î","i").replace("û","u")
        with open("BooksData/RawData.pkl", "wb") as file:
            pickle.dump(books, file)
    booksData = list()
    bookNames = set()
    bookAuthors = set()
    bookStores = set()
    
    for book in books.split("\n"):
        lastSlash = book.rindex("/")
        name = book[:lastSlash-1].strip()
        otherInfo = book[lastSlash + 1:]
        secondaryInfo = otherInfo.split("( ")
        author = secondaryInfo[0].strip()
        bookstore = secondaryInfo[1].removesuffix(' )').strip()
        booksData.append([name, author, bookstore])
        bookNames.add(name)
        bookAuthors.add(author)
        bookStores.add(bookstore)

    with open("BooksData/BooksData.pkl","wb") as file:
        pickle.dump(booksData,file)

    with open("BooksData/BookNames.pkl","wb") as file:
        pickle.dump(bookNames,file)

    with open("BooksData/BookAuthors.pkl","wb") as file:
        pickle.dump(bookAuthors,file)

    with open("BooksData/BookStores.pkl","wb") as file:
        pickle.dump(bookStores,file)

def initialization():
    global DRIVER
    DRIVER = webdriver.Chrome()
    DRIVER.get("https://www.kitapyurdu.com/")
    DRIVER.maximize_window()

def getBookPageAndPrice():
    booksList: list
    with open("BooksData/BooksData.pkl", "rb") as file:
        booksList = pickle.load(file)
    try:
        with open("BooksData/Issues.pkl", "wb") as file:
            dataCouldntGet = pickle.load(file)
    except:
        dataCouldntGet = list()

    print(booksList)
    print(dataCouldntGet)
    
    absoluteBookData = list()
    nameInput: WebElement
    tempBookList = deepcopy(booksList)

    for bookData in tempBookList:
        nameInput = WebDriverWait(DRIVER,3).until(EC.presence_of_element_located((By.ID, "search-input")))
        nameInput.clear()
        try:
            nameInput.send_keys(bookData[0]," ",bookData[2][:-5],Keys.ENTER)
            bookPageLink = WebDriverWait(DRIVER, 3).until(EC.presence_of_element_located((By.CLASS_NAME, "cover"))).find_element(By.TAG_NAME, "a").get_attribute("href")
        except:
            try:
                nameInput = WebDriverWait(DRIVER,3).until(EC.presence_of_element_located((By.ID, "search-input")))
                nameInput.clear()
                nameInput.send_keys(bookData[0].replace("-", " "),Keys.ENTER)
                bookPageLink = WebDriverWait(DRIVER, 3).until(EC.presence_of_element_located((By.CLASS_NAME, "cover"))).find_element(By.TAG_NAME, "a").get_attribute("href")
            except:
                try:
                    DRIVER.find_element(By.LINK_TEXT, "Benzer Sonuçları da Göster").click()
                    bookPageLink = WebDriverWait(DRIVER, 3).until(EC.presence_of_element_located((By.CLASS_NAME, "cover"))).find_element(By.TAG_NAME, "a").get_attribute("href")
                except Exception as e:
                    dataCouldntGet.append(bookData)
                    print(f"An error occured while trying to get the WebPage of {bookData[0]}.")
                    print(f"Exception: {e}")
                    continue
        try:
            DRIVER.get(bookPageLink)
            attributeTable: WebElement
            attributeTable = WebDriverWait(DRIVER, 3).until(EC.presence_of_element_located((By.CLASS_NAME, "attributes")))
            tableRow: WebElement
            tableRow = attributeTable.find_elements(By.TAG_NAME, "tr")
            row: WebElement
            for row in tableRow:
                tdatas = row.find_elements(By.TAG_NAME, "td")
                if tdatas[0].text == "Sayfa Sayısı:":
                    pageNum = tdatas[1].text
                    break
            price = DRIVER.find_element(By.CLASS_NAME, "price__item").text
            booksList.remove(bookData)
            bookData.append(int(pageNum))
            bookData.append(float(price.replace(",", ".")))
            absoluteBookData.append(bookData)
        except Exception as e:
            dataCouldntGet.append(bookData)
            print(f"An error occured while trying to get the data of {bookData[0]}.")
            print(f"Exception: {e}")

    sortedPage = sorted(absoluteBookData, key= lambda data: data[3])
    sortedPrice = sorted(absoluteBookData, key= lambda data: data[4])
    with open("BooksData/Issues.pkl", "wb") as file:
        pickle.dump(dataCouldntGet, file)
    with open("BooksData/BooksData.pkl", "wb") as file:
        pickle.dump(booksList, file)
    with open("BooksData/BooksAbsoluteDataSortedPage.pkl", "ab") as file:
        pickle.dump(sortedPage, file)
    with open("BooksData/BooksAbsoluteDataSortedPrice.pkl", "ab") as file:
        pickle.dump(sortedPrice, file)

#with open("BooksData/BooksAbsoluteDataSortedPage.pkl","rb") as file:
#    data = pickle.load(file)
#import pandas
#pandas.DataFrame(data).to_excel("BooksData/table.xlsx", index=False, header=False)